(* Este archivo define la gramatica formal del lenguaje infantil en notacion EBNF. *)
(* Sirve como base del analizador sintactico y muestra una logica secuencial, *)
(* guiada y cercana al pensamiento de un niño principiante. *)

programa         = separadores , { sentencia , separadores } , EOF ;

sentencia        = crear_cajita
                 | guardar
                 | mostrar
                 | preguntar
                 | repetir
                 | si_pasa ;

crear_cajita     = "crear_cajita" , identificador , "como" , tipo ;
guardar          = "guardar" , identificador , "con" , expresion ;
mostrar          = "mostrar" , expresion ;
preguntar        = "preguntar" , cadena , "guardar_en" , identificador ;
repetir          = "repetir" , expresion , "veces" , bloque ;
si_pasa          = "si_pasa" , condicion , "entonces" , bloque , [ "si_no_pasa" , bloque ] ;

bloque           = separadores , { sentencia , separadores } , "fin" ;

condicion        = condicion_y , { "o" , condicion_y } ;
condicion_y      = condicion_no , { "y" , condicion_no } ;
condicion_no     = [ "no" ] , comparacion ;
comparacion      = expresion , [ operador_relacional , expresion ] ;

expresion        = termino , { operador_aditivo , termino } ;
termino          = factor , { operador_multiplicativo , factor } ;
factor           = numero
                 | cadena
                 | booleano
                 | identificador ;

tipo             = "numero" | "decimal" | "texto" | "si_no" ;
booleano         = "verdadero" | "falso" ;

operador_aditivo         = "+" | "-" ;
operador_multiplicativo  = "*" | "/" ;
operador_relacional      = "mayor_que"
                         | "menor_que"
                         | "igual_a"
                         | "diferente_de"
                         | "mayor_o_igual"
                         | "menor_o_igual" ;

identificador    = letra , { letra | digito | "_" } ;
numero           = digito , { digito } , [ "." , digito , { digito } ] ;
cadena           = '"' , { caracter } , '"' ;
separadores      = { salto_linea } ;
